languageCode = 'en-us'
title = 'blogpage'
theme = 'paper'

# change image cache folder location
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
twitter = 'takoislongboi'
github = 'user8595'
avatar = 'https://i.postimg.cc/xdK7tsKy/Foto-Profil.png'
name = 'user859'
bio = 'a digital journal.'
